export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const ADD_NEW_ITEM_SUCCESS = 'ADD_NEW_ITEM_SUCCESS';

export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';

export const CHANGE_ITEM_SUCCESS = 'CHANGE_ITEM_SUCCESS';
